package com.myspace.deposit_retention;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class EventModel implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String EVENT;
	private java.util.Date EVENT_DATE;

	public EventModel() {
	}

	public java.lang.String getEVENT() {
		return this.EVENT;
	}

	public void setEVENT(java.lang.String EVENT) {
		this.EVENT = EVENT;
	}

	public java.util.Date getEVENT_DATE() {
		return this.EVENT_DATE;
	}

	public void setEVENT_DATE(java.util.Date EVENT_DATE) {
		this.EVENT_DATE = EVENT_DATE;
	}

	public EventModel(java.lang.String EVENT, java.util.Date EVENT_DATE) {
		this.EVENT = EVENT;
		this.EVENT_DATE = EVENT_DATE;
	}

}